config/routes.rb
Rails.application.routes.draw do

  root "articles#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible

    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :body,  presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord

  include Visible
  
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    #VALID_STATUSES = ['public', 'private', 'archived']

    #included do
    #    validates :status, inclusion: { in: VALID_STATUSES }
    #end

    class_methods do
        def public_count
            where(status: 'public').count
        end
    end

    def archived?
        status == 'archived'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private 
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end

    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
    <section class="form">
        <div class="title">
            <strong><%= form.label :title %><br></strong>
            <%= form.text_field :title %>
            <% @article.errors.full_messages_for(:title).each do |message| %>
                <div><%= message %>
            <% end %>
        </div>

        <div class="body">
            <strong><%= form.label :body %><br></strong>
            <%= form.text_area :body %>
            <% @article.errors.full_messages_for(:body).each do |message| %>
                <div><%= message %>
            <% end %>
        </div>
        <!--
        <div>
            <%= form.label :status %>
            <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
        </div>
        -->

        <div>
            <%= form.submit %><br>
        </div>
    </section>
<% end %>

app/views/articles/edit.html.erb
<center><h1 style="color: #e0e0e0;letter-spacing: 20px;">EDIT POST</h1>
</center>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<section class="top">
 <h1 style="color: #e0e0e0;letter-spacing: 20px">POST</h1>
    
</section>
<section class="articles">
    <% @articles.each do |article| %>
        <% unless article.archived? %>
            <div class="summary">
                <h4><%= article.title %></h2>
                <p>
                    <%= truncate(article.body, length: 50, separator: ' ') %>
                </p>
                <%= link_to "Read More", article, class: "button" %>
            </div>
            <% end %>
    <% end %>
</section> 

app/views/articles/new.html.erb
<h1 class="title">New Post</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<section class="article-details">
    <div class="top">
        <h1><%= @article.title %></h1>
        <div class="actions">
            <%= link_to "Edit", edit_article_path(@article), class: 'button' %>
            <%= link_to "Delete", article_path(@article), method: :delete, data: {
             turbo_method: :delete,
                        turbo_confirm: "Are you sure you want to Delete?" 
                        } , class: 'button' %>
        </div>
    </div>
    <p class="article-body">
        <%= @article.body %>
    </p>
    <h2>Comments</h2>
    <%= render @article.comments %>

    <h2>Add a comment:</h2>
    <%= render 'comments/form' %>
</section>

app/views/comments/_comment.html.erb
<div class= "comment">
    <% unless comment.archived? %>
        <p>
            <strong><%= comment.commenter%>:</strong>
            <%= comment.body %>
        </p>
        <p>
            <%= link_to "Delete", [comment.article, comment], data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure you want to Delete?" 
                        } , class: 'button' %>
        </p>
    <%end%>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build] do |form| %>
    <section class="add-comment">
        <p>
            <%= form.label :commenter %><br>
            <%= form.text_field :commenter, :required => true%>
        </p>
        </section>
        <p >
            <%= form.label :body%><br>
            <%= form.text_area :body,  :required => true%>
        </p>
       
        <div class="bottom">
        
                <%= form.submit %>
              
            </p>
        </div>
    
<% end %>

app/views/layouts/_header.html.erb
<header>
    <nav>
        <h1><%= link_to "BLOG" ,root_path%>
        <span>
<%= link_to "APP", root_path, style: "color: #db0303; text-decoration: none "%>        </span , root_path></h1>
        <ul class= "left">
            <li>
                <%= link_to "HOME", root_path%>
            </li>
            <div class="navbar__links">
            
            <%= link_to "+ New Post", new_article_path %>
        </div>
        </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>